"use client";
import {useEffect,useMemo,useState} from "react";
const helpData={
 announcements:["State & County Announcements","Official public notices published through the Riverside County Government portal. Notices shown here are informational unless the notice itself states a formal legal effect."],
 governance:["County Government","Review the current Governor, cabinet, Senate and ruling party information maintained by the County network. This page is public information and does not provide administrative editing access."],
 agencies:["County Agencies","Browse agencies and departments participating in the Riverside County government network. Agency descriptions, administrators, extensions and legal authorities are maintained centrally."],
 business:["Business Transaction Filing","Businesses can report taxable or deductible business activity using this filing form. The submission enters the shared county financial ledger and may be associated with a RinCEN Wirtschaftsprofil by the Department of Finance."],
 search:["County Search","Filter the public agency and government information currently loaded on this website. This is not a full records request or court-record search."]
};
function Help({topic,enabled,onOpen}){if(!enabled)return null;return <button className="info-dot" title="Information" onClick={()=>onOpen(topic)}>i</button>}
export default function Portal(){
 const [tab,setTab]=useState('home'),[gov,setGov]=useState({agencies:[],government:{}}),[ann,setAnn]=useState([]),[rules,setRules]=useState([]),[help,setHelp]=useState(false),[drawer,setDrawer]=useState(null),[q,setQ]=useState(''),[receipt,setReceipt]=useState(null);
 useEffect(()=>{Promise.all([fetch('/api/governance').then(r=>r.json()),fetch('/api/announcements').then(r=>r.json()),fetch('/api/business-filings').then(r=>r.json())]).then(([g,a,t])=>{setGov(g.state||{agencies:[],government:{}});setAnn(a.announcements||[]);setRules(t.rules||[])})},[]);
 const filtered=useMemo(()=>gov.agencies.filter(a=>!q||`${a.name} ${a.abbreviation} ${a.description}`.toLowerCase().includes(q.toLowerCase())),[gov,q]);
 const openHelp=k=>setDrawer(helpData[k]||["Information","This area provides public Riverside County information and services."]);
 async function submitFiling(e){e.preventDefault();const f=new FormData(e.currentTarget);const payload=Object.fromEntries(f.entries());payload.certified=f.get('certified')==='on';const r=await fetch('/api/business-filings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const p=await r.json();if(!r.ok)return alert(p.error||'Submission failed');setReceipt(p);e.currentTarget.reset()}
 return <div className="site">
  <div className="official-bar"><span className="flag-css" aria-hidden="true"></span><span>Official website of the Riverside County Government</span><button onClick={()=>openHelp('governance')}>Here's how you know⌄</button><div className="official-right"><button onClick={()=>setHelp(v=>!v)}>{help?'Hide help':'Show help'}</button><span>Public Information</span></div></div>
  <header className="public-nav"><div className="brand"><img src="/assets/county-government-seal.png"/><div><strong>RIVERSIDE COUNTY</strong><span>STATE OF CALIFORNIA</span></div></div><nav>{[['home','Home'],['announcements','Announcements'],['governance','Government'],['agencies','Agencies'],['business','Business Filing']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</nav></header>
  {tab==='home'&&<main><section className="hero"><video autoPlay muted playsInline onLoadedMetadata={e=>{e.currentTarget.currentTime=2}} onTimeUpdate={e=>{if(e.currentTarget.duration&&e.currentTarget.currentTime>=e.currentTarget.duration-.15)e.currentTarget.currentTime=2}}><source src="/assets/county-home.mp4" type="video/mp4"/></video><div className="shade"></div><div className="hero-content"><img src="/assets/county-government-seal.png"/><h1>Riverside County Government</h1><p>Public services, county agencies and official information.</p><div className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search county agencies and services"/><Help topic="search" enabled={help} onOpen={openHelp}/></div><div className="hero-links"><button onClick={()=>setTab('agencies')}>Find an agency</button><button onClick={()=>setTab('announcements')}>County announcements</button><button onClick={()=>setTab('business')}>File business transaction</button></div></div></section><section className="home-grid"><article><h2>State & County Announcements <Help topic="announcements" enabled={help} onOpen={openHelp}/></h2>{ann.slice(0,3).map(a=><div className="notice" key={a.id}><small>{a.category}</small><strong>{a.title}</strong><p>{a.summary}</p></div>)}</article><article className="gov-card"><img src="/assets/county-seal.png"/><h2>County Governance</h2><p>Learn about county leadership, agencies and the administrative structure of Riverside County.</p><button onClick={()=>setTab('governance')}>View County Government →</button></article></section></main>}
  {tab==='announcements'&&<main className="content"><div className="page-title"><h1>Announcements <Help topic="announcements" enabled={help} onOpen={openHelp}/></h1><p>Official public notices and county information.</p></div><div className="notice-list">{ann.map(a=><article key={a.id}><small>{a.category} · {new Date(a.published_at).toLocaleDateString()}</small><h2>{a.title}</h2><p>{a.summary}</p>{a.body&&<p>{a.body}</p>}</article>)}</div></main>}
  {tab==='agencies'&&<main className="content"><div className="page-title"><h1>County Agencies <Help topic="agencies" enabled={help} onOpen={openHelp}/></h1><p>Departments and public bodies participating in Riverside County government.</p></div><input className="agency-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search agencies"/><div className="agency-grid">{filtered.map(a=><article key={a.id}><div className="agency-logo"><img src={a.logoPath||'/assets/county-seal.png'} onError={e=>e.currentTarget.src='/assets/county-seal.png'}/></div><small>{a.category}</small><h2>{a.name}</h2><p>{a.description}</p><dl><dt>Administrator</dt><dd>{a.administrator||'—'}</dd><dt>Extension</dt><dd>{a.extension||'—'}</dd><dt>Legal authority</dt><dd>{a.legalAuthority||'—'}</dd></dl></article>)}</div></main>}
  {tab==='governance'&&<main className="content"><div className="page-title"><h1>County Government <Help topic="governance" enabled={help} onOpen={openHelp}/></h1><p>Executive leadership and Riverside Senate.</p></div><section className="governor"><img src="/assets/governor-seal.png"/><div><small>GOVERNOR</small><h2>{gov.government?.governor?.name||'William Bracken'}</h2><strong>{gov.government?.governor?.party||'New Founding Fathers of America'}</strong><p>{gov.government?.governor?.biography}</p></div></section><h2>State Cabinet</h2><div className="cabinet-grid">{(gov.government?.cabinet||[]).map((x,i)=><article key={i}><strong>{x.office}</strong><span>{x.name}</span></article>)}</div><h2>Riverside Senate</h2><div className="senate-grid">{(gov.government?.senate||[]).map((x,i)=><article key={i}><strong>{x.name}</strong><span>{x.party}</span><small>{x.district} · {x.committee}</small></article>)}</div></main>}
  {tab==='business'&&<main className="content"><div className="page-title"><h1>Business Transaction Filing <Help topic="business" enabled={help} onOpen={openHelp}/></h1><p>Riverside County Business Activity Return — public filing service.</p></div><form className="tax-form" onSubmit={submitFiling}><div className="form-head"><div className="form-number">RC<br/><b>BT-1040</b></div><div><small>RIVERSIDE COUNTY DEPARTMENT OF FINANCE</small><h2>Business Transaction Activity Return</h2><p>For reportable business income and deductions</p></div><div className="year">{new Date().getFullYear()}</div></div><div className="row three"><label>Business name<input name="businessName" required/></label><label>Reporter / responsible person<input name="reporterName" required/></label><label>Contact reference<input name="contact"/></label></div><div className="row three"><label>Transaction date<input name="occurredAt" type="date" required/></label><label>Activity classification<select name="categoryCode" required><option value="">Select category</option>{rules.map(r=><option key={r.code} value={r.code}>{r.name} — {(Number(r.rate_basis_points)/100).toFixed(2)}%</option>)}</select></label><label>Entry type<select name="direction"><option value="income">Income / taxable receipt (+)</option><option value="expense">Expense / allowable deduction (−)</option></select></label></div><div className="amount-row"><span>Reportable amount</span><span>$</span><input name="amount" type="number" step="0.01" min="0.01" required/></div><label className="description">Description of transaction<textarea name="description" rows="5" placeholder="Describe the transaction, service, sale, contract, expense, or other reportable activity."/></label><div className="cert"><label><input type="checkbox" name="certified" required/> I certify that the information provided in this filing is accurate to the best of my knowledge and is submitted on behalf of the named business.</label></div><button className="submit-return">SUBMIT BUSINESS RETURN</button>{receipt&&<div className="receipt"><strong>Filing received: {receipt.reference}</strong><span>Calculated tax impact: ${Number(receipt.taxImpact).toFixed(2)}</span><span>{receipt.linkedProfile?'Automatically linked to a county financial profile.':'Awaiting RinCEN business-profile association.'}</span></div>}</form></main>}
  <footer><img src="/assets/county-seal.png"/><div><strong>Riverside County Government</strong><span>State of California · Public Information Portal</span></div><span>Official county network</span></footer>
  {drawer&&<aside className="help-drawer"><button onClick={()=>setDrawer(null)}>×</button><small>PUBLIC ASSISTANCE</small><h2>{drawer[0]}</h2><p>{drawer[1]}</p><p>This assistance explains the website interface and does not itself create legal rights, deadlines or agency authority.</p></aside>}
 </div>}
